function [ rawFID, twix ] = readHighOrderTwix(datFile, acq_manifest, firstAcquisition)
% Read sequential High-Order GIRF image ADCs from a Siemens Twix .dat file.
%
% Arguments:
%   datFile:          Siemens raw-data .dat file
%   acq_manifest:     acquisition table generated by
%                     write_GSTF_Scholten2023_HighOrder.m, or path to the
%                     corresponding acq_manifest_HighOrder.mat file
%   firstAcquisition: optional first image-ADC index in the Twix file. This
%                     is only needed if the image stream contains extra
%                     acquisitions before/after the High-Order GIRF ADCs.
%
% Returns:
%   rawFID: sequential image data [numROP, coils, acquisitions]
%   twix:   mapVBVD object used to read the data
%
% This function deliberately uses twix.image.unsorted(), because the
% High-Order acquisition manifest is the source of truth for PE, slice,
% polarity, triangle, and repetition ordering.

if nargin < 3
    firstAcquisition = [];
end

%% Check mapVBVD %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if exist('mapVBVD','file') ~= 2
    error(['mapVBVD was not found on the MATLAB path. Add mapVBVD before ' ...
        'calling readHighOrderTwix().']);
end

%% Read acquisition manifest %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ischar(acq_manifest) || isstring(acq_manifest)
    manifestData = load(acq_manifest);
    if ~isfield(manifestData,'acq_manifest')
        error('Manifest file does not contain acq_manifest.');
    end
    acq_manifest = manifestData.acq_manifest;
end

if ~istable(acq_manifest)
    error('acq_manifest must be a table or a path to a manifest .mat file.');
end

expectedAcquisitions = height(acq_manifest);
if expectedAcquisitions < 1
    error('Acquisition manifest is empty.');
end

%% Read Siemens Twix data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
twix = mapVBVD(datFile);

% VD/VE/XA multi-raid files can return a cell array. The final measurement
% is normally the image measurement generated by the Pulseq sequence.
if iscell(twix)
    nonEmpty = find(~cellfun(@isempty,twix));
    if isempty(nonEmpty)
        error('mapVBVD returned an empty multi-raid dataset.');
    end
    twix = twix{nonEmpty(end)};
end

if ~isfield(twix,'image') || isempty(twix.image)
    error('Twix file does not contain an image data stream.');
end

% Keep the acquired ADC samples unchanged. In particular, do not remove
% readout oversampling or average repetitions before manifest-based sorting.
twix.image.flagRemoveOS = 0;
twix.image.flagDoAverage = 0;
twix.image.flagAverageReps = 0;
twix.image.flagAverageSets = 0;
twix.image.flagIgnoreSeg = 0;

rawAll = twix.image.unsorted();
rawAll = reshape(rawAll,size(rawAll,1),size(rawAll,2),[]);
numAvailable = size(rawAll,3);

%% Select High-Order acquisition range %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(firstAcquisition)
    if numAvailable ~= expectedAcquisitions
        error(['Twix image stream contains %d ADCs, while the acquisition ' ...
            'manifest contains %d rows. If the Twix file includes extra ' ...
            'image ADCs, specify firstAcquisition explicitly.'], ...
            numAvailable,expectedAcquisitions);
    end
    firstAcquisition = 1;
end

firstAcquisition = round(firstAcquisition);
lastAcquisition = firstAcquisition + expectedAcquisitions - 1;

if firstAcquisition < 1 || lastAcquisition > numAvailable
    error(['Requested acquisition range [%d, %d] is outside the Twix image ' ...
        'stream containing %d ADCs.'], ...
        firstAcquisition,lastAcquisition,numAvailable);
end

rawFID = rawAll(:,:,firstAcquisition:lastAcquisition);

fprintf(['Read High-Order GIRF Twix data: [%d samples, %d coils, %d ADCs] ' ...
    'from image acquisitions %d:%d.\n'], ...
    size(rawFID,1),size(rawFID,2),size(rawFID,3), ...
    firstAcquisition,lastAcquisition);

end
