function [ kspace, axisManifest ] = sortHighOrderAcquisitions(rawFID, acq_manifest, axisName, nPE, numSlices)
% Sort sequential High-Order GIRF ADCs into the Fast_GIRF k-space format.
%
% Arguments:
%   rawFID:       sequential ADC data [numROP, coils, acquisitions]
%                 Additional trailing dimensions are flattened in acquisition order.
%   acq_manifest: acquisition table generated by
%                 write_GSTF_Scholten2023_HighOrder.m, or path to the .mat file
%   axisName:     'x', 'y', or 'z'
%   nPE:          full PE matrix size (e.g. 5 or 7)
%   numSlices:    number of offset slices
%
% Returns:
%   kspace:       [numROP, coils, nPE, nPE, slices, 2*numTriangles,
%                  cardiacPhase(1), ADC(1), repetitions]
%   axisManifest: subset of the acquisition manifest for the selected axis
%
% Elliptical PE acquisitions are inserted into their corresponding full-grid
% positions. Unacquired PE locations remain zero, allowing the existing
% Fast_GIRF 2D FFT processing to be used unchanged.

%% Read manifest %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ischar(acq_manifest) || isstring(acq_manifest)
    manifestData = load(acq_manifest);
    if ~isfield(manifestData,'acq_manifest')
        error('Manifest file does not contain acq_manifest.');
    end
    acq_manifest = manifestData.acq_manifest;
end

if ~istable(acq_manifest)
    error('acq_manifest must be a table or a path to a manifest .mat file.');
end

requiredVariables = {'Axis','Repetition','Triangle','Polarity', ...
    'PE1Index','PE2Index','SliceIndex'};
for i=1:length(requiredVariables)
    if ~ismember(requiredVariables{i},acq_manifest.Properties.VariableNames)
        error(['Manifest is missing required variable: ',requiredVariables{i}]);
    end
end

%% Prepare raw acquisition array %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(rawFID) || size(rawFID,1) == 0 || size(rawFID,2) == 0
    error('rawFID is empty.');
end
rawFID = reshape(rawFID,size(rawFID,1),size(rawFID,2),[]);

if size(rawFID,3) ~= height(acq_manifest)
    error(['Number of sequential ADCs (%d) does not match manifest rows (%d). ' ...
        'rawFID must contain only the image ADCs generated by the High-Order sequence, in acquisition order.'], ...
        size(rawFID,3),height(acq_manifest));
end

if nargin < 4 || isempty(nPE)
    nPE = max([acq_manifest.PE1Index; acq_manifest.PE2Index]);
end
if nargin < 5 || isempty(numSlices)
    numSlices = max(acq_manifest.SliceIndex);
end

if ~ismember(axisName,{'x','y','z'})
    error('axisName must be ''x'', ''y'', or ''z''.');
end

axisMask = strcmp(string(acq_manifest.Axis),axisName);
axisRows = find(axisMask);
axisManifest = acq_manifest(axisMask,:);

if isempty(axisRows)
    error(['No acquisitions for axis ',axisName,' were found in the manifest.']);
end

numRep = max(acq_manifest.Repetition(axisMask));
numTriangles = max(acq_manifest.Triangle(axisMask));
numROP = size(rawFID,1);
numCoils = size(rawFID,2);

kspace = zeros(numROP,numCoils,nPE,nPE,numSlices,2*numTriangles,1,1,numRep,'like',rawFID);
occupied = false(nPE,nPE,numSlices,2*numTriangles,numRep);

%% Sort acquisitions %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for i=1:length(axisRows)
    row = axisRows(i);

    pe1 = acq_manifest.PE1Index(row);
    pe2 = acq_manifest.PE2Index(row);
    sl = acq_manifest.SliceIndex(row);
    tri = acq_manifest.Triangle(row);
    rep = acq_manifest.Repetition(row);
    pol = acq_manifest.Polarity(row);

    if pol > 0
        triPol = 2*tri - 1;
    elseif pol < 0
        triPol = 2*tri;
    else
        error('Manifest contains a zero gradient polarity.');
    end

    if pe1 < 1 || pe1 > nPE || pe2 < 1 || pe2 > nPE
        error('Manifest PE index is outside the requested nPE matrix.');
    end
    if sl < 1 || sl > numSlices
        error('Manifest slice index is outside the requested slice range.');
    end
    if tri < 1 || tri > numTriangles || rep < 1 || rep > numRep
        error('Manifest triangle/repetition index is outside the allocated range.');
    end

    if occupied(pe1,pe2,sl,triPol,rep)
        error(['Duplicate manifest destination for %s-axis: PE=(%d,%d), ' ...
            'slice=%d, triangle/polarity=%d, repetition=%d.'], ...
            axisName,pe1,pe2,sl,triPol,rep);
    end
    occupied(pe1,pe2,sl,triPol,rep) = true;

    kspace(:,:,pe1,pe2,sl,triPol,1,1,rep) = rawFID(:,:,row);
end

if nnz(occupied) ~= length(axisRows)
    error('Sorted acquisition occupancy does not match the number of manifest rows.');
end

fprintf(['Sorted High-Order GIRF acquisitions for %s-axis: %d ADCs -> ' ...
    '[%d %d %d %d %d %d 1 1 %d].\n'], ...
    axisName,length(axisRows),numROP,numCoils,nPE,nPE,numSlices,2*numTriangles,numRep);

end
